#!/bin/bash
set -ex

######################
##   Prerequisites  ##
######################

mkdir ~/.kube
cp  .kube/config ~/.kube/config
URL=https://$(kubectl get node -o wide | awk {'print $6'} | head -n 4 | tail -n 1):30380
git clone https://$username:$password@github.com/mayadata-io/oep.git
echo $URL
