#!/bin/bash

set -e

path=$(pwd)
mkdir ~/.kube
cp .gcp/config ~/.kube/config

echo $SDK_TOKEN > key.json
gcloud auth activate-service-account --key-file=key.json
gcloud config set project openebs-ci
export GOOGLE_APPLICATION_CREDENTIALS="$path/key.json"

######################################## Applying e2e-CRD
echo "***Applying e2e-crd***********"
kubectl apply -f utils/e2e-crd.yml

bash utils/e2e-cr jobname:teaming-invite-check jobphase:Waiting
bash utils/e2e-cr jobname:teaming-invite-check jobphase:Running 
bash utils/e2e-cr jobname:teaming-account-resource-access-check jobphase:Waiting
bash utils/e2e-cr jobname:teaming-change-role-check jobphase:Waiting
bash utils/e2e-cr jobname:teaming-change-role-negative-check jobphase:Waiting

git clone https://$username:$password@github.com/mayadata-io/oep.git
echo "Validate teaming invitation process --------------------------------------------"
kubectl create -f oep/litmus/director/invite/run_litmus_test.yml
test_name=invite-check
echo $test_name
litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo $litmus_pod
job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
while [[ "$job_status" != "Completed" ]]
do 
    job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
    sleep 6
done
kubectl logs -f $litmus_pod -n litmus
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo $testResult
if [ "$testResult" != Pass ]
then 
    exit 1; 
else
    bash utils/e2e-cr jobname:teaming-invite-check jobphase:Completed
fi