#!/bin/bash
set -ex

######################
##   Prerequisites  ##
######################

mkdir ~/.kube
cp  .kube/config ~/.kube/config


kubectl get po


URL=https://$(kubectl get node -o wide | awk {'print $6'} | head -n 4 | tail -n 1):30380

echo "This is DOP $URl" 

wget https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz

tar -zxvf helm-v2.14.3-linux-amd64.tar.gz

mv linux-amd64/helm /usr/local/bin/helm

echo $HELM_RBAC > HELM_RBAC.yaml

#cat HELM_RBAC.yaml

#kubectl apply -f HELM_RBAC.yaml

helm init

sleep 45

helm version


######################
##    deploy        ##
######################

echo "deploying DOP" 

git clone https://$username:$password@github.com/mayadata-io/director-charts-internal.git

git checkout dop-e2e

cd director-charts-internal/e2e

kubectl apply -f docker-secret.yaml

helm install --name mod .

kubectl get po 
